
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 01 20:10:49 EST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EDGE = 2;
  public static final int error = 1;
  public static final int VERTEX = 3;
  public static final int EOF = 0;
}

